import numpy as np
from t3toolbox.tucker_tensor_train import TuckerTensorTrain as T3, T3Weights, t3_weighted_norm, t3_absorb_weights
np.random.seed(0)
def rel(a, b): return float(np.linalg.norm(a-b)/np.linalg.norm(b))
def run(x, y, label, **kw):
    ref = x.to_dense() * y.to_dense()
    for m in ['form_then_round', 'inplace_fused', 'swap']:
        try:
            z = x.t3m(y, method=m, **kw)
            cap = kw.get('max_tt_ranks'); capT = kw.get('max_tucker_ranks')
            ok_tt = (cap is None) or all(r <= (cap if isinstance(cap,int) else cap[i]) for i, r in enumerate(z.tt_ranks))
            ok_tk = (capT is None) or all(n <= (capT if isinstance(capT,int) else capT[i]) for i, n in enumerate(z.tucker_ranks))
            print(f'  {label:34s} {m:16s} ranks {z.ranks}  caps honored tt={ok_tt} tucker={ok_tk}  relerr {rel(z.to_dense(), ref):.2e}')
        except Exception as e:
            print(f'  {label:34s} {m:16s} RAISED {type(e).__name__}: {str(e)[:90]}')
for stack in [(), (2,)]:
    x = T3.randn((5,6,7), (2,3,2), (2,2,2,3), stack_shape=stack)
    y = T3.randn((5,6,7), (3,2,2), (3,3,2,2), stack_shape=stack)
    print(f'--- TAILS != 1, stack={stack}: x.tt_ranks={x.tt_ranks} y.tt_ranks={y.tt_ranks}; exact product bonds (6,6,4,6)')
    run(x, y, 'max_tt=30,max_tk=30 (non-binding)', max_tt_ranks=30, max_tucker_ranks=30)
    run(x, y, 'max_tt=3,max_tk=3', max_tt_ranks=3, max_tucker_ranks=3)
    run(x, y, 'max_tt=(1,3,3,1)', max_tt_ranks=(1,3,3,1))
    run(x, y, 'max_tucker=4 only', max_tucker_ranks=4)
    if stack == ():
        run(x, y, 'rtol=1e-12', rtol=1e-12)
        run(x, y, 'rtol=1e-2', rtol=1e-2)
    # left tail only / right tail only
    xl = T3.randn((5,6,7), (2,3,2), (2,2,2,1), stack_shape=stack); yl = T3.randn((5,6,7), (3,2,2), (1,3,2,1), stack_shape=stack)
    print(f'--- only x has r0=2, stack={stack}')
    run(xl, yl, 'max_tt=3,max_tk=3', max_tt_ranks=3, max_tucker_ranks=3)
    xr = T3.randn((5,6,7), (2,3,2), (1,2,2,3), stack_shape=stack)
    print(f'--- only x has rd=3, stack={stack}')
    run(xr, yl, 'max_tt=3,max_tk=3', max_tt_ranks=3, max_tucker_ranks=3)
print('--- TAILS = 1 control')
x = T3.randn((5,6,7), (2,3,2), (1,2,2,1)); y = T3.randn((5,6,7), (3,2,2), (1,3,2,1))
run(x, y, 'max_tt=3,max_tk=3', max_tt_ranks=3, max_tucker_ranks=3)
run(x, y, 'rtol=1e-2', rtol=1e-2)

print('--- other ops with tails != 1')
x = T3.randn((5,6,7), (2,3,2), (2,2,2,3))
def tryit(label, f):
    try: print(f'  [{label}] OK ->', f())
    except Exception as e: print(f'  [{label}] RAISED {type(e).__name__}: {str(e)[:120]}')
tryit('t3svd', lambda: (x.t3svd()[0].ranks, rel(x.t3svd()[0].to_dense(), x.to_dense())))
tryit('t3svd max_tt=2', lambda: (x.t3svd(max_tt_ranks=2)[0].ranks))
tryit('rank_adjustment_sweep', lambda: (x.rank_adjustment_sweep().ranks, rel(x.rank_adjustment_sweep().to_dense(), x.to_dense())))
tryit('rank_adjustment_sweep L2R', lambda: (x.rank_adjustment_sweep('left_to_right').ranks, rel(x.rank_adjustment_sweep('left_to_right').to_dense(), x.to_dense())))
tryit('continuation_ranks', lambda: x.continuation_ranks())
tryit('share', lambda: T3.randn((6,6,7),(2,2,2),(2,2,2,3)).share((0,0,1)).ranks)
tryit('has_numerically_minimal_ranks', lambda: x.has_numerically_minimal_ranks())
tryit('is_left_orthogonal(t3svd)', lambda: x.t3svd()[0].is_left_orthogonal())
tryit('minimal_ranks', lambda: x.minimal_ranks)
tryit('norm', lambda: float(x.norm()) - np.linalg.norm(x.to_dense()))
tryit('inner', lambda: float(x.inner(x)) - np.sum(x.to_dense()**2))
tryit('from_t3svd weights consistent', lambda: T3Weights.from_t3svd(x).is_consistent_with(x))
tryit('sum', lambda: float(x.sum()) - x.to_dense().sum())
tryit('sum(axis=0)', lambda: rel(x.sum(axis=0).to_dense(), x.to_dense().sum(axis=0)))
tryit('sum_stack', lambda: rel(T3.randn((5,6,7),(2,3,2),(2,2,2,3),stack_shape=(3,)).sum_stack().to_dense(), 0*np.ones(1)+T3.randn((5,6,7),(2,3,2),(2,2,2,3),stack_shape=(3,)).sum_stack().to_dense()))
xs3 = T3.randn((5,6,7),(2,3,2),(2,2,2,3),stack_shape=(3,))
tryit('sum_stack exact', lambda: rel(xs3.sum_stack().to_dense(), xs3.to_dense().sum(axis=0)))
tryit('x + x', lambda: rel((x+x).to_dense(), 2*x.to_dense()))
tryit('x + 1.5', lambda: rel((x+1.5).to_dense(), x.to_dense()+1.5))
tryit('probe', lambda: rel(x.probe([np.ones(5), np.ones(6), np.ones(7)])[1], x.to_dense().sum(axis=(0,2))))
tryit('entries', lambda: float(x.entries([1,2,3])) - x.to_dense()[1,2,3])
